### ISSUE TITLE
collectedBy is inverseOf itself

### ISSUE THREAD

**Issue by acka47** [dini-ag-kim/holding-ontology#37]
When I get the RDF of the ontology via command line – e.g. `curl -L -H "Accept: text/turtle" http://purl.org/ontology/holding#collectedBy` it includes this triple:

```
holding:collectedBy owl:inverseOf holding:collectedBy, holding:collects .
```

You should fix that. Strangely, this isn't shown in the HTML view.

**Comment by cKlee** [comment]
This seems to be solved.
